// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelbilityApp.Infrastructure.Data;

#nullable disable

namespace TravelbilityApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TravelbilityAppDbContext))]
    [Migration("20250731135832_SeedPropertiesPhotosTable")]
    partial class SeedPropertiesPhotosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-ab12-c3de4f567890"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f3fbb67-83a1-4c8a-9376-77d5bc93e96e",
                            Email = "peter@abv.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "PETER@ABV.COM",
                            NormalizedUserName = "PETER@ABV.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJWqUtNTFyrCflRJ5mDSJBQ/+6zWDN0EOs71CJjYR+CdSVrC5EmSgljJfheS0OdepA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "XKYK5BIDWLG3ED57QZYQHRLUZMMUVYWS",
                            TwoFactorEnabled = false,
                            UserName = "peter@abv.com"
                        },
                        new
                        {
                            Id = new Guid("f7e8d9a0-b1c2-34d5-6789-f01ab2c345de"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5d4fdb87-23b1-4da2-9e3e-a8b4df7a283f",
                            Email = "george@abv.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "GEORGE@ABV.COM",
                            NormalizedUserName = "GEORGE@ABV.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKmgDhog2RCm4iw5ZcCQKxQMzwb43ifsn+Wiz+Dbfuqirl8NkgDWsqQxxDZz6QokGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "JTHY3GADWFA4KD67TFYUIUQNLJMNXYAS",
                            TwoFactorEnabled = false,
                            UserName = "george@abv.com"
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.BedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BedTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "90 cm x 190 cm",
                            Name = "Single Bed"
                        },
                        new
                        {
                            Id = 2,
                            Description = "90 cm x 190 cm each",
                            Name = "Twin Bed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "135 cm x 190 cm",
                            Name = "Double Bed"
                        },
                        new
                        {
                            Id = 4,
                            Description = "150 cm x 200 cm",
                            Name = "Queen Bed"
                        },
                        new
                        {
                            Id = 5,
                            Description = "180 cm x 200 cm",
                            Name = "King Bed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Size varies",
                            Name = "Sofa Bed"
                        },
                        new
                        {
                            Id = 7,
                            Description = "90 cm x 190 cm each",
                            Name = "Bunk Bed"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Size varies",
                            Name = "Trundle"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Size varies",
                            Name = "Murphy Bed"
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsForAccessibility")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WhereStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsForAccessibility = true,
                            Name = "Higher level toilet",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 2,
                            IsForAccessibility = false,
                            Name = "Airport shuttle",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 3,
                            IsForAccessibility = false,
                            Name = "Free Wi-Fi",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 4,
                            IsForAccessibility = false,
                            Name = "Pets allowed",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 5,
                            IsForAccessibility = true,
                            Name = "Toilet with grab rails",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 6,
                            IsForAccessibility = false,
                            Name = "Room service",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 7,
                            IsForAccessibility = true,
                            Name = "Wheelchair accessible",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 8,
                            IsForAccessibility = true,
                            Name = "Visual aids: Tactile signs",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 9,
                            IsForAccessibility = false,
                            Name = "Swimming Pool",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 10,
                            IsForAccessibility = true,
                            Name = "Electric vehicle charging station",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 11,
                            IsForAccessibility = false,
                            Name = "Family rooms",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 12,
                            IsForAccessibility = true,
                            Name = "Visual aids: Braille",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 13,
                            IsForAccessibility = true,
                            Name = "Lower bathroom sink",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 14,
                            IsForAccessibility = false,
                            Name = "Fitness centre",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 15,
                            IsForAccessibility = false,
                            Name = "Non-smoking rooms",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 16,
                            IsForAccessibility = true,
                            Name = "Emergency cord in bathroom",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 17,
                            IsForAccessibility = false,
                            Name = "Parking",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 18,
                            IsForAccessibility = false,
                            Name = "Restaurant",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 19,
                            IsForAccessibility = true,
                            Name = "Auditory guidance",
                            WhereStatus = 3
                        },
                        new
                        {
                            Id = 20,
                            IsForAccessibility = false,
                            Name = "Spa and wellness centre",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 21,
                            IsForAccessibility = false,
                            Name = "Private bathroom",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 22,
                            IsForAccessibility = false,
                            Name = "Sea view",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 23,
                            IsForAccessibility = false,
                            Name = "Balcony",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 24,
                            IsForAccessibility = false,
                            Name = "Kitchen / kitchenette",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 25,
                            IsForAccessibility = false,
                            Name = "Terrace",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 26,
                            IsForAccessibility = false,
                            Name = "Coffee / tea maker",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 27,
                            IsForAccessibility = false,
                            Name = "Air conditioning",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 28,
                            IsForAccessibility = false,
                            Name = "Fireplace",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 29,
                            IsForAccessibility = false,
                            Name = "TV",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 30,
                            IsForAccessibility = false,
                            Name = "Flat-screen TV",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 31,
                            IsForAccessibility = false,
                            Name = "Private pool",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 32,
                            IsForAccessibility = false,
                            Name = "Soundproofing",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 33,
                            IsForAccessibility = false,
                            Name = "Electric kettle",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 34,
                            IsForAccessibility = false,
                            Name = "Rooftop pool",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 35,
                            IsForAccessibility = false,
                            Name = "Refrigerator",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 36,
                            IsForAccessibility = false,
                            Name = "Patio",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 37,
                            IsForAccessibility = false,
                            Name = "Hairdryer",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 38,
                            IsForAccessibility = false,
                            Name = "Heating",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 39,
                            IsForAccessibility = true,
                            Name = "Upper floors accessible by elevator",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 40,
                            IsForAccessibility = true,
                            Name = "Roll-in shower",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 41,
                            IsForAccessibility = true,
                            Name = "Shower chair",
                            WhereStatus = 1
                        },
                        new
                        {
                            Id = 42,
                            IsForAccessibility = true,
                            Name = "Accessible Parking",
                            WhereStatus = 2
                        },
                        new
                        {
                            Id = 43,
                            IsForAccessibility = false,
                            Name = "Mini Fridge",
                            WhereStatus = 1
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("CheckIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckOut")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StarsCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            Address = "Palm Jumeirah, Palm Jumeirah, Dubai, United Arab Emirates",
                            CheckIn = new TimeOnly(15, 0, 0),
                            CheckOut = new TimeOnly(6, 0, 0),
                            CreatedAt = new DateTime(2025, 7, 31, 13, 58, 31, 878, DateTimeKind.Utc).AddTicks(9874),
                            Description = "FIVE Palm Jumeirah Dubai features its own private beach as well as 5 outdoor swimming pools, including a 180 ft long option, running through the heart of the resort. Guests can enjoy free WiFi throughout the property.\r\n\r\nThe hotel has 470 guest rooms and suites, spread across 16 floors, decorated in a simple yet elegant style with views of the Arabian Gulf.\r\n\r\nThe resort has an array of facilities, including dining venues hosted by world-class chefs, a modern spa and a karaoke room at Maiden Shanghai.\r\n\r\nA landmark on the trunk of the iconic Palm Jumeirah, FIVE Palm Jumeirah Dubai is strategically located for convenient access to Dubai’s business districts, as well as the city’s many exciting tourist and entertainment attractions.\r\n\r\nThe resort is also accessible from Dubai International Airport (DXB), which is 20 mi away and Al Maktoum International Airport (DWC), which 26 mi away. Mall of Emirates is 7 mi away, while Dubai Mall is 14 mi from the property.",
                            Name = "FIVE Palm Jumeirah Dubai",
                            PropertyTypeId = 3,
                            PublisherId = new Guid("a1b2c3d4-e5f6-7890-ab12-c3de4f567890"),
                            StarsCount = 5,
                            Status = 3,
                            UpdatedAt = new DateTime(2025, 7, 31, 13, 58, 31, 878, DateTimeKind.Utc).AddTicks(9879)
                        },
                        new
                        {
                            Id = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            Address = "Barbaros Hayrettin Pasa Mah. 1999 Sok. Esenyurt, 34522 Istanbul, Turkey",
                            CheckIn = new TimeOnly(14, 0, 0),
                            CheckOut = new TimeOnly(0, 0, 0),
                            CreatedAt = new DateTime(2025, 7, 31, 13, 58, 31, 879, DateTimeKind.Utc).AddTicks(204),
                            Description = "Located in business area in Beylikduzu, 1 km from Tuyap Convention Centre, Hilton Garden Inn Istanbul Beylikduzu features indoor pool and 24/7 fitness centre. Free WiFi access is available in all areas.\n\nModern rooms are fitted with a flat-screen TV. Some units include a seating area for your convenience. Every room comes with a private bathroom. For your comfort, you will find free toiletries and a hair dryer.\n\nThere is a 24-hour front desk, providing room service at the property. Laundry, dry cleaning and ironing services are also provided upon request at an additional charge.\n\nGuests can enjoy their meals at the on-site restaurant. The lobby bar is ideal for having a drink and relaxing after a busy day.\n\nThe hotel is 35 km from Istanbul’s historic centre, where guests can visit Topkapi Palace, Blue Mosque, and Hagia Sophia Museum. Istanbul Airport is a 50-minute drive away.",
                            Name = "Hilton Garden Inn Istanbul Beylikduzu",
                            PropertyTypeId = 1,
                            PublisherId = new Guid("a1b2c3d4-e5f6-7890-ab12-c3de4f567890"),
                            StarsCount = 4,
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 7, 31, 13, 58, 31, 879, DateTimeKind.Utc).AddTicks(205)
                        },
                        new
                        {
                            Id = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            Address = "Boduthakurufaanu Magu, 20006 Male City, Maldives",
                            CheckIn = new TimeOnly(14, 0, 0),
                            CheckOut = new TimeOnly(12, 0, 0),
                            CreatedAt = new DateTime(2025, 7, 31, 13, 58, 31, 879, DateTimeKind.Utc).AddTicks(228),
                            Description = "Beachfront Location: Summer Beach Maldives in Male City offers direct beachfront access with stunning sea views. Guests enjoy a terrace and outdoor seating area, perfect for relaxation.\r\n\r\nComfortable Accommodations: Rooms feature air-conditioning, private bathrooms, and modern amenities such as free WiFi, mini-bars, and flat-screen TVs. Family rooms and interconnected rooms cater to all travelers.\r\n\r\nDining Experience: The family-friendly restaurant serves Indian, Italian, Thai, and international cuisines, including vegetarian and halal options. Breakfast includes local specialties, fresh pastries, and a variety of beverages.\r\n\r\nConvenient Services: The guest house provides a free airport shuttle service, 24-hour front desk, concierge, and tour desk. Additional amenities include a coffee shop, child-friendly buffet, and free WiFi throughout the property.",
                            Name = "Summer Beach Maldives",
                            PropertyTypeId = 5,
                            PublisherId = new Guid("f7e8d9a0-b1c2-34d5-6789-f01ab2c345de"),
                            StarsCount = 4,
                            Status = 3,
                            UpdatedAt = new DateTime(2025, 7, 31, 13, 58, 31, 879, DateTimeKind.Utc).AddTicks(228)
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.PropertyFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("RoomId");

                    b.HasIndex("PropertyId", "FacilityId", "RoomId")
                        .IsUnique()
                        .HasFilter("[RoomId] IS NOT NULL");

                    b.ToTable("PropertiesFacilities");
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.PropertyPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoomId");

                    b.ToTable("PropertiesPhotos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b51a7e4b-6efa-42e0-834e-87433b3c45c5"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            Url = "https://c.ekstatic.net/dex-media/416/Five-Palm-Jumeirah-Dubai-Desktop-HotelDetails-1-1-637327495922065801.jpg"
                        },
                        new
                        {
                            Id = new Guid("e9a351b1-39fe-483e-bdd7-e37dfb30ed12"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/117749607.jpg?k=a7377ffe413a077a665056fa5058bdf9d3ff47000e8f703d59192535b92a198e&o="
                        },
                        new
                        {
                            Id = new Guid("d922b714-5e40-4fd1-bb21-cbec290c8e46"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            Url = "https://c.ekstatic.net/dex-media/416/Five-Palm-Jumeirah-Dubai-Desktop-HotelDetails-1-2-637327495922065801.jpg"
                        },
                        new
                        {
                            Id = new Guid("14e34147-cb15-4b1c-98b8-f8e54e360f90"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            Url = "https://c.ekstatic.net/dex-media/416/Five-Palm-Jumeirah-Dubai-Desktop-HotelDetails-1-4-637327495922065801.jpg"
                        },
                        new
                        {
                            Id = new Guid("912b8d66-354c-4a7f-9beb-0cdfb857a6f5"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            Url = "https://c.ekstatic.net/dex-media/416/Five-Palm-Jumeirah-Dubai-Desktop-HotelDetails-1-3-637327495922065801.jpg"
                        },
                        new
                        {
                            Id = new Guid("6d6da45e-e3e9-4a23-8465-e0c0f76520c1"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("135ea1ed-239f-437b-8ec7-9035dbb7f5b3"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568077.jpg?k=90b8087fad5a98e35d8c991681db1b308ba69e3c92c44ec5e79bbfbbb4d10343&o="
                        },
                        new
                        {
                            Id = new Guid("a181cadc-482f-4c24-8194-a26a2d02706e"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("135ea1ed-239f-437b-8ec7-9035dbb7f5b3"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568080.jpg?k=c809ee1a5895d43812c9051d967825ba872b84157dac7163a66390991160ca09&o="
                        },
                        new
                        {
                            Id = new Guid("c84bac8c-64ab-4e5b-b701-a6e8ddf3fa42"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("135ea1ed-239f-437b-8ec7-9035dbb7f5b3"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642564429.jpg?k=adc6bcbad98434f49672fb7a52c62ade54673fb1866ceecf04c24ebf00691ace&o="
                        },
                        new
                        {
                            Id = new Guid("0a4feeda-1d8f-4fa5-9ede-2b7915333691"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("135ea1ed-239f-437b-8ec7-9035dbb7f5b3"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568129.jpg?k=6231e8c3ce340683d6a5ea3a4c31319573f6fcb70e768fc8daac4dd4c30371b2&o="
                        },
                        new
                        {
                            Id = new Guid("2fd4837b-34d2-475c-82b7-f652a14bd0b0"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("135ea1ed-239f-437b-8ec7-9035dbb7f5b3"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568137.jpg?k=82e16dadd5a3d9e3c23afcd917a8b061f71d537da515aa9bac7b920088738391&o="
                        },
                        new
                        {
                            Id = new Guid("0057040d-0289-4973-967c-d8f39f4c890f"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("e961fee4-03ab-4d12-a1cb-d25849b9a1c8"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568934.jpg?k=af600b8487d4f95512b7af7c3de4a42a5dd340445bb98c5f3ade0a834af8ec61&o="
                        },
                        new
                        {
                            Id = new Guid("bdc8cf17-0ef8-41dc-b35d-c1d7cc74cce7"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("e961fee4-03ab-4d12-a1cb-d25849b9a1c8"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568942.jpg?k=e74666193c057d13d8c57edf9eaa2b0f6f0c3e6be0b31b99cf088eda27de7afc&o="
                        },
                        new
                        {
                            Id = new Guid("6bed0ce3-0f53-40ec-8115-6fd5bed9f78b"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("e961fee4-03ab-4d12-a1cb-d25849b9a1c8"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568957.jpg?k=9a61b99aecfb26925d9e04b1e09b6ff791da5121f027acc671ac23ceae1f5783&o="
                        },
                        new
                        {
                            Id = new Guid("6267856f-35b0-4082-b9b7-56916a721bfd"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("e961fee4-03ab-4d12-a1cb-d25849b9a1c8"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642564429.jpg?k=adc6bcbad98434f49672fb7a52c62ade54673fb1866ceecf04c24ebf00691ace&o="
                        },
                        new
                        {
                            Id = new Guid("e947a4cf-8234-4f25-8fbb-f5dc27a6a35c"),
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomId = new Guid("e961fee4-03ab-4d12-a1cb-d25849b9a1c8"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/642568863.jpg?k=a175cad3389263f9e0bbd2460d55aeeef4fa932cbbfaabf8c581de08f9680d8d&o="
                        },
                        new
                        {
                            Id = new Guid("19f9f6ad-57e9-4542-ae0f-59b257b1c0c0"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105483.jpg?k=d381f915f7e9311bf64734cbb87742eec40a834264ba1c1237f7e18f7276060a&o="
                        },
                        new
                        {
                            Id = new Guid("4a3a37b6-6053-47b4-94f2-85c8ee855890"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/513203867.jpg?k=d2899a2b7c4e9951abb20c934dfefbcc7c7e60c025ee3feca3f7483913ab877c&o=&hp=1"
                        },
                        new
                        {
                            Id = new Guid("dc2d0612-9244-42fe-93af-6eae90d82fe4"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105543.jpg?k=adbc5414747997bd2c7d69ec85b08d84fd379719f210e610d60fa75220500abb&o=&hp=1"
                        },
                        new
                        {
                            Id = new Guid("bf91f7ee-8b77-4c10-9408-89f9a0b9d053"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max300/484105537.jpg?k=e47db70ecd10f46adc980421e2495483a18a256147949ec75fecc5fb108a87de&o="
                        },
                        new
                        {
                            Id = new Guid("c74d2b15-1b87-40b1-8ea3-6bfb14e60c3f"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max500/484806261.jpg?k=82afaa65c2e8396120999c45e40bb3ec760a91a793f9f93e85abc1e678f0a7a1&o="
                        },
                        new
                        {
                            Id = new Guid("8964ff08-2294-4e2d-b81e-89ecd80ffb55"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            RoomId = new Guid("534ed86f-6b26-4b46-8070-5be3770199f9"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105547.jpg?k=70acbfe097e254504627d28cb087caa803f79d54c9c93036d2b9bb954a1f2b8c&o="
                        },
                        new
                        {
                            Id = new Guid("241c766d-976e-4314-9207-d75208a77982"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            RoomId = new Guid("534ed86f-6b26-4b46-8070-5be3770199f9"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105593.jpg?k=8927a514e029b26f105f355056c4332e2e103162729faae719189f4f8c9b9079&o="
                        },
                        new
                        {
                            Id = new Guid("ba1547ec-2302-4fb8-bd03-d67b3d1a7be4"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            RoomId = new Guid("534ed86f-6b26-4b46-8070-5be3770199f9"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105598.jpg?k=a2c196492a682c671ccafff03e52eae0bcde337f883ad6a5068082063e5c6e01&o="
                        },
                        new
                        {
                            Id = new Guid("2ce742c0-4174-492b-93eb-a92adf84858f"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            RoomId = new Guid("534ed86f-6b26-4b46-8070-5be3770199f9"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105552.jpg?k=399c0e58cb01ed3c1d8f645e51855a25f31007bed9439f43119e51ccf0971b8b&o="
                        },
                        new
                        {
                            Id = new Guid("3f1ad636-2959-4d43-9ac9-ddf4f754d24e"),
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            RoomId = new Guid("534ed86f-6b26-4b46-8070-5be3770199f9"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/484105561.jpg?k=c2d2be660be85b2dc70294c906194dc75e042342e1a928192d4dd2adb1336c84&o="
                        },
                        new
                        {
                            Id = new Guid("2b84e1d5-9f79-4b47-880a-4536e911120c"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398767814.jpg?k=d9962306000f2dfa5aab8437d8b693ee3973b24b5d8e21b0acf6ea0895394d15&o="
                        },
                        new
                        {
                            Id = new Guid("bdd354f6-cc31-4b49-8034-e37acbebb6a9"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398767820.jpg?k=6724f5c42976d9f85d6ea43dd55ac74f19f39236bda8a94b22172f5c73983e7d&o=&hp=1"
                        },
                        new
                        {
                            Id = new Guid("a7ca5e80-dff9-44ed-a14f-df8df60fb4b6"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398915704.jpg?k=331223231b2f2dcbcb9e6aecbc74f8f0b2e2020b288c150b60cfc34b447fa32e&o="
                        },
                        new
                        {
                            Id = new Guid("7dfa6fe4-d1eb-4ed8-ae69-2ad93757b16e"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398915707.jpg?k=888ffd15c625eead51e21c81f8095e705bba850546c580cf272213135913ee16&o="
                        },
                        new
                        {
                            Id = new Guid("c6ad4f65-7ff5-47e2-90b2-9229fae5feae"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398767817.jpg?k=e625a8c84d8c55e279931f86ac0bad61436de6f200203801138490f956413528&o=&hp=1"
                        },
                        new
                        {
                            Id = new Guid("199009c0-8e75-4d01-83cd-a6a57aeaa74a"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            RoomId = new Guid("141e8179-d711-4dec-8ec6-7ec29d47b2b2"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398788806.jpg?k=59ada28a447085e1328c22f48683ae09006e132f368ed5042157dd29b1c5576a&o="
                        },
                        new
                        {
                            Id = new Guid("7b357dad-3835-4b32-ba63-b54a4d583aed"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            RoomId = new Guid("141e8179-d711-4dec-8ec6-7ec29d47b2b2"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398788793.jpg?k=f4ea5a1232e4bc6911c85019239bdcd36fcaed2006bba78a97f9f598c4f05ce2&o="
                        },
                        new
                        {
                            Id = new Guid("a127ac41-686e-4643-aa6b-89c2c29881a2"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            RoomId = new Guid("141e8179-d711-4dec-8ec6-7ec29d47b2b2"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398788808.jpg?k=bdc82b35918e4f921bca93cf7979baedefba3016b51d820f51b67b76d32da45b&o="
                        },
                        new
                        {
                            Id = new Guid("c9316103-6786-40fc-8596-83acec72892a"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            RoomId = new Guid("141e8179-d711-4dec-8ec6-7ec29d47b2b2"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398788815.jpg?k=a6957bfcf1b646c76ea9a2dc946898bb9d077cf8284f1056af1916a861197f8c&o="
                        },
                        new
                        {
                            Id = new Guid("17221edc-72c8-49c4-ae5b-16a81c33a16d"),
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            RoomId = new Guid("141e8179-d711-4dec-8ec6-7ec29d47b2b2"),
                            Url = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/398788797.jpg?k=e78b542c382a6c006bb6393db978c8dd1b5e9279e71c65cd6abd02b069bba9c4&o="
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Entire homes & apartments"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apartments"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hotels"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Guest houses"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Villas"
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MainBedTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfUnits")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<double>("SizeInSquareMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MainBedTypeId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("135ea1ed-239f-437b-8ec7-9035dbb7f5b3"),
                            Description = "Featuring a private balcony and seating, this air conditioned room offers a large double bed, a 55 inch smart TV.",
                            IsDeleted = false,
                            MainBedTypeId = 3,
                            MaxGuests = 4,
                            NumberOfUnits = 3,
                            PricePerNight = 129.99m,
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomTypeId = 8,
                            SizeInSquareMeters = 25.0
                        },
                        new
                        {
                            Id = new Guid("e961fee4-03ab-4d12-a1cb-d25849b9a1c8"),
                            Description = "This spacious suite is consisted of of 1 bedroom, a seating area and 1 bathroom with a walk-in shower and a bath. The air-conditioned suite offers a flat-screen TV with streaming services, soundproof walls, a mini-bar, a tea and coffee maker as well as city views. The unit offers 1 bed.",
                            IsDeleted = false,
                            MainBedTypeId = 5,
                            MaxGuests = 2,
                            NumberOfUnits = 11,
                            PricePerNight = 357m,
                            PropertyId = new Guid("bae99276-1865-4c63-899c-093d3b85f014"),
                            RoomTypeId = 6,
                            SizeInSquareMeters = 55.0
                        },
                        new
                        {
                            Id = new Guid("534ed86f-6b26-4b46-8070-5be3770199f9"),
                            Description = "The double room offers air conditioning, a tea and coffee maker, a safe deposit box, heating and a flat-screen TV. The unit offers 2 beds.",
                            IsDeleted = false,
                            MainBedTypeId = 2,
                            MaxGuests = 2,
                            NumberOfUnits = 7,
                            PricePerNight = 109.98m,
                            PropertyId = new Guid("bcb4f072-ecca-43c9-ab26-c060c6f364e4"),
                            RoomTypeId = 3,
                            SizeInSquareMeters = 39.0
                        },
                        new
                        {
                            Id = new Guid("141e8179-d711-4dec-8ec6-7ec29d47b2b2"),
                            Description = "The air-conditioned suite features 2 bedrooms and 2 bathrooms with a bath and a shower. Featuring a balcony with sea views, this suite also provides a mini-bar and a flat-screen TV with cable channels. The unit offers 2 beds.",
                            IsDeleted = false,
                            MainBedTypeId = 3,
                            MaxGuests = 3,
                            NumberOfUnits = 5,
                            PricePerNight = 197m,
                            PropertyId = new Guid("b9ec059b-5951-4d13-9fd1-ede0802dc76e"),
                            RoomTypeId = 8,
                            SizeInSquareMeters = 43.0
                        });
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsForAccessibility")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsForAccessibility = false,
                            Name = "Single Room"
                        },
                        new
                        {
                            Id = 2,
                            IsForAccessibility = false,
                            Name = "Double Room"
                        },
                        new
                        {
                            Id = 3,
                            IsForAccessibility = false,
                            Name = "Twin Room"
                        },
                        new
                        {
                            Id = 4,
                            IsForAccessibility = false,
                            Name = "Deluxe Room"
                        },
                        new
                        {
                            Id = 5,
                            IsForAccessibility = false,
                            Name = "Family Room"
                        },
                        new
                        {
                            Id = 6,
                            IsForAccessibility = false,
                            Name = "Suite"
                        },
                        new
                        {
                            Id = 7,
                            IsForAccessibility = false,
                            Name = "Studio"
                        },
                        new
                        {
                            Id = 8,
                            IsForAccessibility = true,
                            Name = "Accessible Room"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Property", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.PropertyType", "PropertyType")
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.ApplicationUser", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyType");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.PropertyFacility", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.Property", "Property")
                        .WithMany("Facilities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.Room", "Room")
                        .WithMany("Facilities")
                        .HasForeignKey("RoomId");

                    b.Navigation("Facility");

                    b.Navigation("Property");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.PropertyPhoto", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.Property", "Property")
                        .WithMany("Photos")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.Room", "Room")
                        .WithMany("Photos")
                        .HasForeignKey("RoomId");

                    b.Navigation("Property");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Room", b =>
                {
                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.BedType", "MainBedType")
                        .WithMany()
                        .HasForeignKey("MainBedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.Property", "Property")
                        .WithMany("Rooms")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelbilityApp.Infrastructure.Data.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainBedType");

                    b.Navigation("Property");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Property", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Photos");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("TravelbilityApp.Infrastructure.Data.Models.Room", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
